schemaVersion: 2.2.2
metadata:
  name: community-ansible-dev-tools-container
components:
  - name: tooling-container
    container:
      image: ghcr.io/nilashishc/community-ansible-dev-tools-container:latest
      memoryRequest: 200M
      memoryLimit: 6Gi
      cpuRequest: 250m
      cpuLimit: 2000m
      args: ['tail', '-f', '/dev/null']
